version: '3'

services:
   express-app:
      build:
         context: ./server
      container_name: expressserver
      hostname: expressserver
      ports:
         - "3000:3000"
      networks:
         - backend-net
      depends_on:
         - db
   db:
     container_name: mongo-db
     image: mongo
     volumes:
       - .data:/data/db
     ports:
       - "27017:27017"
     networks:
       - backend-net

   webserver:
     build:
       context: ./nginx
     container_name: webserver
     hostname: webserver
     ports:
       - "80:80"
     depends_on:
       - express-app
     networks:
       - backend-net
    
networks:
  backend-net:
    external: true
